[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "reefblast"
version = "0.1.4"
description = "Blast-fishing shock loading of gas-laden coral canopies"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [
    { name = "Sandy H. S. Herho" },
    { name = "Agus W. Jatmiko"},    
    { name = "Rizki D. Permana" },
    { name = "Iwan P. Anwar" },
    { name = "Alfita P. Handayani" },
    { name = "Faruq Khadami" },
    { name = "Karina A. Sujatmiko" },
    { name = "Rusmawan Suwarman"},
    { name = "Deny J. Puradimaja"},
    { name = "Dasapta E. Irawan" }
]
keywords = ["blast fishing", "coral reef", "underwater explosion",
            "bubbly liquid", "spallation", "Indonesia"]
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Physics",
]
dependencies = [
    "numpy>=1.24",
    "scipy>=1.10",
    "matplotlib>=3.7",
    "pillow>=10.0",
]

[project.optional-dependencies]
lint = ["pycodestyle>=2.11", "pydocstyle>=6.3"]

[tool.setuptools]
packages = ["reefblast"]

[tool.pydocstyle]
convention = "pep257"
